# Generated by Django 2.1.7 on 2019-05-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='title', max_length=50),
            preserve_default=False,
        ),
    ]
